"""Replaced posting_date with posted_text

Revision ID: 6e54fe9bb66f
Revises: 
Create Date: 2025-07-03 20:01:29.444908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e54fe9bb66f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted_text', sa.String(length=20), nullable=True))
        batch_op.drop_column('posting_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posting_date', sa.DATE(), nullable=True))
        batch_op.drop_column('posted_text')

    # ### end Alembic commands ###
